# Generated by Django 3.0.3 on 2020-02-29 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_is_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_doc',
            field=models.BooleanField(),
        ),
    ]
