# Generated by Django 3.0.3 on 2020-03-07 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livechat', '0002_auto_20200301_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
