# Generated by Django 3.0.3 on 2020-03-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livechat', '0004_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note',
            field=models.CharField(max_length=500),
        ),
    ]
