# Generated by Django 3.0.3 on 2020-03-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooddata',
            name='apettite',
            field=models.IntegerField(choices=[('1', 'Very poor'), ('2', 'poor'), ('3', 'fair'), ('4', 'good'), ('5', 'very good')]),
        ),
    ]
