# Generated by Django 3.0.3 on 2020-03-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientdata', '0003_auto_20200306_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pressuredata',
            old_name='data',
            new_name='dia',
        ),
        migrations.AddField(
            model_name='pressuredata',
            name='sys',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
